### ISSUE TITLE
Better error logging when cellpose/omnipose fails

### ISSUE THREAD

**Issue by lacan** [BIOP/qupath-extension-cellpose#41]
In case cellpose/omnipose fails, we reach an error where label images cannot be read (because they do not exist)
```
INFO: Cellpose2D: ValueError: ERROR: no images in --dir folder
INFO: Reading objects from file Temp_896_4839_z0_t0_cp_masks.tif
INFO: All tiles and objects read, now resolving overlaps
ERROR: javax.imageio.IIOException: Can't read input file!
java.lang.RuntimeException: javax.imageio.IIOException: Can't read input file!
    at qupath.ext.biop.cellpose.Cellpose2D.lambda$processCellposeFiles$21(Cellpose2D.java:777)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by Can't read input file!        at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
        at qupath.ext.biop.cellpose.Cellpose2D.readObjectsFromFile(Cellpose2D.java:1329)
        at qupath.ext.biop.cellpose.Cellpose2D.lambda$processCellposeFiles$21(Cellpose2D.java:775)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
ERROR: Cannot invoke "java.util.Collection.stream()" because the return value of "qupath.ext.biop.cellpose.Cellpose2D$TileFile.getCandidates()" is null in 1-Segment_Tubules_fromMarkerList.groovy at line number 62
qupath.ext.biop.cellpose.Cellpose2D.lambda$detectObjectsImpl$8(Cellpose2D.java:417)
    java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
    java.base/java.util.Iterator.forEachRemaining(Unknown Source)
    java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
    java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
    java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
    qupath.ext.biop.cellpose.Cellpose2D.detectObjectsImpl(Cellpose2D.java:418)
    qupath.ext.biop.cellpose.Cellpose2D.lambda$detectObjects$0(Cellpose2D.java:303)
    qupath.ext.biop.cellpose.Cellpose2D.runInPool(Cellpose2D.java:264)
    qupath.ext.biop.cellpose.Cellpose2D.detectObjects(Cellpose2D.java:303)
    org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
    1-Segment_Tubules_fromMarkerList$_run_closure3.doCall(1-Segment_Tubules_fromMarkerList.groovy:62)
    java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    java.base/java.lang.reflect.Method.invoke(Unknown Source)
    org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
    groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
    org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
    groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1008)
    groovy.lang.Closure.call(Closure.java:433)
    groovy.lang.Closure.call(Closure.java:422)
    org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2387)
    org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2372)
    org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2413)
    org.codehaus.groovy.runtime.dgm$207.doMethodInvoke(Unknown Source)
    org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
    1-Segment_Tubules_fromMarkerList.run(1-Segment_Tubules_fromMarkerList.groovy:46)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:331)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:161)
    qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:234)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:1166)
    qupath.lib.gui.scripting.DefaultScriptEditor$3.run(DefaultScriptEditor.java:1534)
    java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.base/java.lang.Thread.run(Unknown Source)
```

catch this error and make it more explicit

**Comment by lacan** [comment]
fixed in latest release
