### ISSUE TITLE
perhaps check that files are written before running environment runner

### ISSUE THREAD

**Issue by lacan** [BIOP/qupath-extension-cellpose#42]
It seems like when writing to a server, the files are either not available to python right away or are locked somehow, making the cellpose-omnipose complain that there are no files in the provided `--dir`
Perhaps we could check on the status. Or we would need a more explicit explanation of

```
INFO: Cellpose2D: Traceback (most recent call last):
INFO: Cellpose2D:   File "D:\conda\conda-envs\omnipose\lib\runpy.py", line 197, in _run_module_as_main
INFO: Cellpose2D:     return _run_code(code, main_globals, None,
INFO: Cellpose2D:   File "D:\conda\conda-envs\omnipose\lib\runpy.py", line 87, in _run_code
INFO: Cellpose2D:     exec(code, run_globals)
INFO: Cellpose2D:   File "D:\conda\conda-envs\omnipose\lib\site-packages\omnipose\__main__.py", line 12, in <module>
INFO: Cellpose2D:     main()
INFO: Cellpose2D:   File "D:\conda\conda-envs\omnipose\lib\site-packages\omnipose\__main__.py", line 9, in main
INFO: Cellpose2D:     cellpose_omni_main(args)
INFO: Cellpose2D:   File "D:\conda\conda-envs\omnipose\lib\site-packages\cellpose_omni\__main__.py", line 207, in main
INFO: Cellpose2D:     image_names = io.get_image_files(args.dir, 
INFO: Cellpose2D:   File "D:\conda\conda-envs\omnipose\lib\site-packages\cellpose_omni\io.py", line 194, in get_image_files
INFO: Cellpose2D:     raise ValueError('ERROR: no images in --dir folder')
INFO: Cellpose2D: ValueError: ERROR: no images in --dir folder
```

**Comment by lacan** [comment]
Probably fixed. Did not manage to reproduce
